
GET http://localhost:3000/users

### 

GET http://localhost:3000/users/651545ab40ea9e1817dea65e

###

PATCH http://localhost:3000/users/651545ab40ea9e1817dea65e
Content-Type: application/json

{
        "emailAddress": "recruitlalit2023@gmail.com",
        "businessName": "Lalit Dungriyal",
		"businessNumber": "7017284567",
		"uniqueCode": "1234",
		"externalReference": "XYZ Mohan",
		"phoneNum": "7017234566",
		"homeAddress": {
			"street": "Gajiwali Gali Number 1",
			"city": "Haridwar",
			"state": "Uttarakhand",
			"postalCode":  "249408"
		},
		"postalAddress": {
			"street": "Uttaranchal Colony Gali no. 1",
			"city": "Ghaziabad",
			"state": "Uttar Pradesh",
			"postalCode":  "201102"
		}
}

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "emailAddress": "lalitdunriyal4@gmail.com",
        "businessName": "Lalit Dungriyal",
		"businessNumber": "7017284567",
		"uniqueCode": "1234",
		"externalReference": "XYZ Mohan",
		"phoneNum": "7017234566",
		"homeAddress": {
			"street": "Gajiwali Gali Number 1",
			"city": "Haridwar",
			"state": "Uttarakhand",
			"postalCode":  "249408"
		},
		"postalAddress": {
			"street": "Uttaranchal Colony Gali no. 1",
			"city": "Ghaziabad",
			"state": "Uttar Pradesh",
			"postalCode":  "201102"
		}
}